---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-fr-esgi-v1beta1-haaudit
  failurePolicy: Fail
  name: mhaaudit.kb.io
  rules:
  - apiGroups:
    - apps.fr.esgi
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - haaudits
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-fr-esgi-v1beta1-haaudit
  failurePolicy: Fail
  name: vhaaudit.kb.io
  rules:
  - apiGroups:
    - apps.fr.esgi
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - haaudits
  sideEffects: None
