---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - daemonsets
  - deployments
  - pods
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps.fr.esgi
  resources:
  - haaudits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.fr.esgi
  resources:
  - haaudits/finalizers
  verbs:
  - update
- apiGroups:
  - apps.fr.esgi
  resources:
  - haaudits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
