apiVersion: apps.fr.esgi/v1beta1
kind: HAAudit
metadata:
  labels:
    app.kubernetes.io/name: haaudit
    app.kubernetes.io/instance: haaudit-sample
    app.kubernetes.io/part-of: ha-audit-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ha-audit-operator
  name: haaudit-sample
spec:
  targets:
    - name: "instance-1-api-ha-test"
      type: "deployment"
      namespace: "default"

    - type: "pod"
      labelSelector:
        matchLabels:
          app: "instance-2-api-ha-test"
      namespace: "default"

    - type: "pod"
      nameRegex: "instance-3-api-ha-test-.*"
      namespace: "default"

  chaosStrategy:
    type: random
    durationSeconds: 3600 # 1 hour
    randomChaosStrategy:
      numberOfPodsToDelete: 4
      frequencyCron: "*/1 * * * *"


