apiVersion: apps.fr.esgi/v1beta1
kind: HAAudit
metadata:
  namespace: default
  labels:
    app.kubernetes.io/name: haaudit
    app.kubernetes.io/instance: haaudit-sample
    app.kubernetes.io/part-of: ha-audit-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ha-audit-operator

  name: haaudit-test
spec:
  report:
    prometheus:
      dumpFrequency: 10
  targets:
    - name: "instance-1-api-ha-test"
      resourceType: "deployment"
      namespace: "default"
      path: "instance-1-api-ha-test.default.svc.cluster.local/ping"
    - resourceType: "pod"
      labelSelector:
        matchLabels:
          app: "instance-2-api-ha-test"
      namespace: "default"
      path: "instance-2-api-ha-test.default.svc.cluster.local/ping"
    - resourceType: "pod"
      nameRegex: "instance-3-api-ha-test-.*"
      namespace: "default"
      path: "instance-3-api-ha-test.default.svc.cluster.local/ping"
  chaosStrategy:
    type: random
    frequencySec: 30
  testSchedule: 1 # 10 seconds
