apiVersion: apps.fr.esgi/v1beta1
kind: HAAudit
metadata:
  labels:
    app.kubernetes.io/name: haaudit
    app.kubernetes.io/instance: haaudit-sample
    app.kubernetes.io/part-of: ha-audit-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ha-audit-operator
  name: haaudit-sample
spec:
  targets:
    - name: "instance-1-api-ha-test"
      kind: "deployment"
      namespace: "default"
      path: "instance-1-api-ha-test.default.svc.cluster.local/ping"
    - kind: "pod"
      labelSelector:
        matchLabels:
          app: "instance-2-api-ha-test"
      namespace: "default"
      path: "instance-2-api-ha-test.default.svc.cluster.local/ping"
    - kind: "pod"
      nameRegex: "instance-3-api-ha-test-.*"
      namespace: "default"
      path: "instance-2-api-ha-test.default.svc.cluster.local/ping"

  chaosStrategy:
    type: random
    frequencySec: 30

  testSchedule: 10 # 10 seconds
  report:
    prometheus:
      address: "prometheus-prometheus-pushgateway.default.svc.cluster.local"
